In [42]:
import pandas as pd 
import numpy as np
import re

# __I/ Import and read data__

In [43]:
df = pd.read_csv(r'D:\Study Documents\Nam 3\Ki 2\Capstone Project 1\Data Cleaned & Visualization\Udemy Data RAW.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29181 entries, 0 to 29180
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Course Name           28484 non-null  object
 1   URL                   28484 non-null  object
 2   Duration              28477 non-null  object
 3   Total Lectures        28484 non-null  object
 4   Level                 28484 non-null  object
 5   Price                 28484 non-null  object
 6   Total Enrollments     28484 non-null  object
 7   Avg Rating Score      28484 non-null  float64
 8   Total Ratings         28484 non-null  object
 9   Last Updated          28484 non-null  object
 10  Language              28484 non-null  object
 11  Subtitles             22527 non-null  object
 12  Total Sections        28448 non-null  object
 13  Instructor Name       28484 non-null  object
 14  Avg Ins Rating        28484 non-null  object
 15  Total Ins Reviews     28484 non-null  object
 16  Total Ins's Students  28484 non-null  object
 17  Total Ins's Courses   28484 non-null  object
 18  Mini_Subject          28484 non-null  object
dtypes: float64(1), object(18)
memory usage: 4.2+ MB

In [44]:
df.head(20)

,Course Name,URL,Duration,Total Lectures,Level,Price,Total Enrollments,Avg Rating Score,Total Ratings,Last Updated,Language,Subtitles,Total Sections,Instructor Name,Avg Ins Rating,Total Ins Reviews,Total Ins's Students,Total Ins's Courses,Mini_Subject
0,The Complete Full-Stack Web Development Bootcamp,https://www.udemy.com/course/the-complete-web-...,61.5 total hours,374 lectures,All Levels,"₫1,599,000","1,426,064 students",4.7,"(428,126 ratings)",Last updated 2/2025,English,"English, Arabic [Auto]",44 sections,"Dr. Angela Yu, Developer and Lead Instructor",4.7 Instructor Rating,"939,239 Reviews","3,085,299 Students",7 Courses,Web Development
1,The Web Developer Bootcamp 2025,https://www.udemy.com/course/the-web-developer...,74 total hours,729 lectures,All Levels,"₫1,539,000","933,673 students",4.7,"(279,281 ratings)",Last updated 3/2025,English,"English [Auto], Arabic [Auto]",75 sections,Colt Steele,4.7 Instructor Rating,"559,192 Reviews","1,852,381 Students",30 Courses,Web Development
2,The Complete JavaScript Course 2025: From Zero...,https://www.udemy.com/course/the-complete-java...,71 total hours,330 lectures,All Levels,"₫1,539,000","974,726 students",4.7,"(220,516 ratings)",Last updated 12/2024,English,"English, Arabic [Auto]",21 sections,Jonas Schmedtmann,4.7 Instructor Rating,"469,876 Reviews","2,113,663 Students",7 Courses,Web Development
3,Angular - The Complete Guide (2025 Edition),https://www.udemy.com/course/the-complete-guid...,56 total hours,757 lectures,All Levels,"₫1,599,000","810,833 students",4.7,"(212,691 ratings)",Last updated 3/2025,English,"English [CC], Arabic [Auto]",46 sections,Maximilian Schwarzmüller,4.7 Instructor Rating,"1,193,752 Reviews","3,267,423 Students",63 Courses,Web Development
4,Build Responsive Real-World Websites with HTML...,https://www.udemy.com/course/design-and-develo...,37.5 total hours,149 lectures,All Levels,"₫1,599,000","443,218 students",4.7,"(112,326 ratings)",Last updated 11/2024,English,"English [CC], Arabic [Auto]",10 sections,Jonas Schmedtmann,4.7 Instructor Rating,"469,876 Reviews","2,113,663 Students",7 Courses,Web Development
5,Modern React with Redux [2024 Update],https://www.udemy.com/course/react-redux/,75.5 total hours,697 lectures,All Levels,"₫1,469,000","325,436 students",4.7,"(88,068 ratings)",Last updated 3/2025,English,"English [Auto], Arabic [Auto]",27 sections,Stephen Grider,4.6 Instructor Rating,"480,423 Reviews","1,497,645 Students",37 Courses,Web Development
6,The Complete Web Developer Course 3.0,https://www.udemy.com/course/the-complete-web-...,31 total hours,222 lectures,All Levels,"₫1,409,000","316,225 students",4.3,"(72,430 ratings)",Last updated 6/2024,English,"English [Auto], Arabic [Auto]",16 sections,Rob Percival,4.4 Instructor Rating,"494,115 Reviews","2,376,277 Students",36 Courses,Web Development
7,Vue - The Complete Guide (incl. Router & Compo...,https://www.udemy.com/course/vuejs-2-the-compl...,32 total hours,333 lectures,All Levels,"₫1,649,000","250,464 students",4.7,"(64,882 ratings)",Last updated 1/2025,English,"English [CC], Arabic [Auto]",29 sections,Maximilian Schwarzmüller,4.7 Instructor Rating,"1,193,752 Reviews","3,267,423 Students",63 Courses,Web Development
8,Master Microservices with Spring Boot and Spri...,https://www.udemy.com/course/microservices-wit...,25.5 total hours,326 lectures,All Levels,"₫1,539,000","277,005 students",4.6,"(55,310 ratings)",Last updated 12/2024,English,"English [CC], Arabic [Auto]",17 sections,in28Minutes Official,4.6 Instructor Rating,"469,568 Reviews","1,801,600 Students",55 Courses,Web Development
9,Understanding TypeScript,https://www.udemy.com/course/understanding-typ...,22.5 total hours,339 lectures,All Levels,"₫1,599,000","263,402 students",4.6,"(54,548 ratings)",Last updated 3/2025,English,"English [CC], Arabic [Auto]",25 sections,Maximilian Schwarzmüller,4.7 Instructor Rating,"1,193,752 Reviews","3,267,423 Students",63 Courses,Web Development
10,Python and Django Full Stack Web Developer Boo...,https://www.udemy.com/course/python-and-django...,32 total hours,198 lectures,All Levels,"₫1,479,000","217,431 students",4.5,"(51,165 ratings)",Last updated 9/2019,English,"English [Auto], Arabic [Auto]",27 sections,Jose Portilla,4.6 Instructor Rating,"1,249,037 Reviews","4,181,187 Students",87 Courses,Web Development
11,JavaScript: Understanding the Weird Parts (202...,https://www.udemy.com/course/understand-javasc...,12.5 total hours,92 lectures,All Levels,"₫1,339,000","195,284 students",4.8,"(48,749 ratings)",Last updated 2/2025,English,"English, Arabic [Auto]",13 sections,Anthony Alicea,4.7 Instructor Rating,"108,539 Reviews","359,954 Students",12 Courses,Web Development
12,"Advanced CSS and Sass: Flexbox, Grid, Animatio...",https://www.udemy.com/course/advanced-css-and-...,28 total hours,126 lectures,Intermediate,"₫1,649,000","218,129 students",4.7,"(45,232 ratings)",Last updated 11/2024,English,"English, Arabic [Auto]",10 sections,Jonas Schmedtmann,4.7 Instructor Rating,"469,876 Reviews","2,113,663 Students",7 Courses,Web Development
13,HTML and CSS for Beginners - Build a Website &...,https://www.udemy.com/course/html-and-css-for-...,9 total hours,81 lectures,All Levels,"₫399,00","371,056 students",4.4,"(36,974 ratings)",Last updated 10/2024,English,"English [Auto], Bulgarian [Auto]",9 sections,"Edwin Diaz | 900,000+ Students",4.4 Instructor Rating,"138,780 Reviews","911,007 Students",46 Courses,Web Development
14,Modern JavaScript From The Beginning 2.0 (2024),https://www.udemy.com/course/modern-javascript...,36.5 total hours,265 lectures,All Levels,"₫1,469,000","122,552 students",4.7,"(34,853 ratings)",Last updated 4/2024,English,"English [Auto], Arabic [Auto]",22 sections,Brad Traversy,4.7 Instructor Rating,"177,865 Reviews","521,237 Students",25 Courses,Web Development
15,The Complete ASP.NET MVC 5 Course,https://www.udemy.com/course/the-complete-aspn...,7.5 total hours,139 lectures,All Levels,"₫1,249,000","140,103 students",4.4,"(34,646 ratings)",Last updated 4/2018,English,"English, Bulgarian [Auto]",11 sections,Mosh Hamedani,4.5 Instructor Rating,"336,784 Reviews","851,598 Students",20 Courses,Web Development
16,Docker & Kubernetes: The Practical Guide [2025...,https://www.udemy.com/course/docker-kubernetes...,23.5 total hours,264 lectures,All Levels,"₫1,699,000","216,725 students",4.7,"(31,924 ratings)",Last updated 1/2025,English,"English [CC], Arabic [Auto]",16 sections,Academind by Maximilian Schwarzmüller,4.7 Instructor Rating,"775,086 Reviews","3,230,052 Students",48 Courses,Web Development
17,Learn and Understand NodeJS,https://www.udemy.com/course/understand-nodejs/,14 total hours,111 lectures,All Levels,"₫1,199,000","134,194 students",4.5,"(30,408 ratings)",Last updated 2/2025,English,"English, Bulgarian [Auto]",12 sections,Anthony Alicea,4.7 Instructor Rating,"108,539 Reviews","359,954 Students",12 Courses,Web Development
18,"Complete React Developer (w/ Redux, Hooks, Gra...",https://www.udemy.com/course/complete-react-de...,42 total hours,346 lectures,All Levels,"₫1,499,000","137,489 students",4.4,"(28,734 ratings)",Last updated 12/2024,English,"English [Auto], Arabic [Auto]",36 sections,Andrei Neagoie,4.6 Instructor Rating,"251,924 Reviews","1,270,596 Students",16 Courses,Web Development
19,The Complete Angular Course: Beginner to Advanced,https://www.udemy.com/course/the-complete-angu...,29.5 total hours,376 lectures,All Levels,"₫1,399,000","117,956 students",4.6,"(27,778 ratings)",Last updated 4/2018,English,"English [Auto], Bulgarian [Auto]",25 sections,Mosh Hamedani,4.5 Instructor Rating,"336,784 Reviews","851,598 Students",20 Courses,Web Development

## __II/ Data Preprocessing__

### __0/ Checking MISSING VALUES__

In [45]:
df.isnull().sum()

Course Name              697
URL                      697
Duration                 704
Total Lectures           697
Level                    697
Price                    697
Total Enrollments        697
Avg Rating Score         697
Total Ratings            697
Last Updated             697
Language                 697
Subtitles               6654
Total Sections           733
Instructor Name          697
Avg Ins Rating           697
Total Ins Reviews        697
Total Ins's Students     697
Total Ins's Courses      697
Mini_Subject             697
dtype: int64

### __1/ Remove DUPLICATE__

In [46]:
df = df.drop_duplicates()

### __2/ Drop null record__

In [47]:
df = df.dropna(subset=['Duration', 'Total Sections'])

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26173 entries, 0 to 29180
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Course Name           26173 non-null  object
 1   URL                   26173 non-null  object
 2   Duration              26173 non-null  object
 3   Total Lectures        26173 non-null  object
 4   Level                 26173 non-null  object
 5   Price                 26173 non-null  object
 6   Total Enrollments     26173 non-null  object
 7   Avg Rating Score      26173 non-null  float64
 8   Total Ratings         26173 non-null  object
 9   Last Updated          26173 non-null  object
 10  Language              26173 non-null  object
 11  Subtitles             20860 non-null  object
 12  Total Sections        26173 non-null  object
 13  Instructor Name       26173 non-null  object
 14  Avg Ins Rating        26173 non-null  object
 15  Total Ins Reviews     26173 non-null  object
 16  Total Ins's Students  26173 non-null  object
 17  Total Ins's Courses   26173 non-null  object
 18  Mini_Subject          26173 non-null  object
dtypes: float64(1), object(18)
memory usage: 4.0+ MB

### __3/ Convert value in DURATION column into HOUR unit__

In [48]:
def convert_to_hour(duration): 
    try:
        value = float(duration.split()[0])
        unit = duration.split()[-1]
        if 'min' in unit: 
            total_hours = value / 60
        else: 
            total_hours = value 
        return round(float(total_hours), 1) 
    except:  
        return np.nan

df['Duration'] =  df['Duration'].apply(convert_to_hour)

### __4/ Clean Price columns__

In [50]:
def convert_Price(price): 
    if pd.isnull(price): 
        return ''
    try:
        numeric_price = int(re.sub(r'\D', '', price))
        if numeric_price < 100000: 
            return numeric_price * 10 
        else: 
            return numeric_price
    except:
        return np.nan
    
df['Price'] = df['Price'].apply(convert_Price)
df['Price']

0        1599000
1        1539000
2        1539000
3        1599000
4        1599000
          ...
29176     399000
29177    1049000
29178    1049000
29179    1049000
29180    1049000
Name: Price, Length: 26173, dtype: int64

### __5/ Convert cols into INT__

In [51]:
def convert_to_int(x): 
    if pd.isnull(x): 
        return 0 
    try: 
        x = (re.sub(r'\D', '', x))
        if x == '':
            return 0
        return int(x) 
    except:
        return 0 

int_col =  ['Total Lectures', 
    'Total Enrollments', 
    'Total Ratings', 
    'Total Sections', 
    'Total Ins Reviews', 
    "Total Ins\'s Students", 
    "Total Ins\'s Courses"
]
for col in int_col: 
    df[col] = df[col].apply(convert_to_int)

### __6/ Convert rating cols into FLOAT__

In [52]:
def convert_rating(x):
    if pd.isnull(x):
        return np.nan
    try:
        value = x.split()[0]
        if value != '--':
            return round(float(value), 1)
        return np.nan
    except:
        return np.nan
    
df['Avg Ins Rating'] = df['Avg Ins Rating'].apply(convert_rating)
df['Avg Rating Score']= df['Avg Rating Score'].apply(lambda x: round(float(x), 1))

### __7/ Convert DATETIME col__

In [53]:
def convert_last_updated(x):
    if pd.isnull(x):
        return ''
    try:
        date_str = x.replace('Last updated ', '')
        date = pd.to_datetime(date_str, format='%m/%Y')
        return date.strftime('%m/%Y')
    except:
        return ''
    
df['Last Updated'] = df['Last Updated'].apply(convert_last_updated)

### __8/ Special character processing__

In [54]:
def clean_subtitles(sub): 
    if pd.isnull(sub): 
        return '' 
    try: 
        sub = re.sub(r'\[CC\]|\[Auto\]', '', sub).strip()
        return sub 
    except: 
        return ''

df['Subtitles'] = df['Subtitles'].apply(clean_subtitles)

### __9/ Make data scraped at the SAME time__

In [55]:
# Lấy ra các bản ghi có total Enrollment lớn nhất cho mỗi URL
max_enrollment_idx = df.groupby("URL")["Total Enrollments"].idxmax()
max_enrollment_df = df.loc[max_enrollment_idx].reset_index(drop=True)

# Tổng hợp tất cả các Mini_Subject duy nhất cho mỗi URL thành một danh sách
categories = df.groupby("URL")["Mini_Subject"].apply(lambda x:  ', '.join(x.unique())).reset_index()

# Kết hợp dữ liệu mới với dữ liệu gốc
df = max_enrollment_df.merge(categories, on="URL", how="left")
df = df.drop(columns = ['Mini_Subject_x']).rename(columns = {'Mini_Subject_y': 'Mini_Subject'})

df

,Course Name,URL,Duration,Total Lectures,Level,Price,Total Enrollments,Avg Rating Score,Total Ratings,Last Updated,Language,Subtitles,Total Sections,Instructor Name,Avg Ins Rating,Total Ins Reviews,Total Ins's Students,Total Ins's Courses,Mini_Subject
0,如何从0-1搭建内容推荐系统,https://www.udemy.com/course/0-1-vvuy/,1.0,9,Beginner,399000,21,5.0,3,09/2021,Simplified Chinese,Simplified Chinese,3,三节课 sanjieke,4.5,19140,29820,1541,Database Design & Development
1,0 dan İleri Seviye Swift 5 ile İOS Mobil Uygul...,https://www.udemy.com/course/0-dan-ileri-seviy...,18.0,95,All Levels,399000,6331,3.1,61,04/2019,Turkish,,11,Hüseyin Can KINCAL,4.1,61,6331,1,Mobile Development
2,0-dan Python proqramlaşdırma ümumi izahda,https://www.udemy.com/course/0-dan-python-proq...,10.0,101,Beginner,399000,8,4.2,3,02/2022,Azeri,,17,Rəsul Eminli,4.2,3,8,1,Programming Languages
3,非同步程式設計從0到1,https://www.udemy.com/course/01-async/,5.0,35,All Levels,2499000,56,4.7,13,11/2020,Traditional Chinese,Traditional Chinese,4,Rico Chen,4.7,91,205,14,Programming Languages
4,01 Day C Code | Learn C Programming with Examp...,https://www.udemy.com/course/01-day-c-code-lea...,3.0,29,All Levels,399000,17956,4.0,167,01/2025,English,English,9,Faisal Zamir,4.3,7032,314342,40,Programming Languages
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24496,دورة تصميم برنامج المبيعات و المخازن بلغة السي...,https://www.udemy.com/course/zwjteeml/,44.0,55,Beginner,399000,19,5.0,1,09/2024,Arabic,,1,Mohammed Nageh,4.9,6,71,7,Programming Languages
24497,金融业务增长秘籍之：核心指标体系的搭建与拆解,https://www.udemy.com/course/zxaylrnf/,0.5,7,Intermediate,399000,30,4.9,3,09/2021,Simplified Chinese,Simplified Chinese,3,三节课 sanjieke,4.5,19060,29704,1541,Data Science
24498,CNC Programming in Hindi (सीएनसी प्रोग्रामिंग ...,https://www.udemy.com/course/zxppxplw/,6.0,11,All Levels,399000,82,4.2,16,07/2022,Hindi,,1,Mech Trainers,4.3,230,946,4,Programming Languages
24499,Zynq Training - Learn Zynq 7000 SOC device on ...,https://www.udemy.com/course/zynq-training-lea...,2.5,21,Beginner,399000,4595,3.7,163,07/2020,English,English,9,Augmented Startups,3.9,3689,57289,26,Software Engineering
24500,Zynq Esencial,https://www.udemy.com/course/zynq7000-esencial/,10.0,24,Intermediate,649000,92,4.8,22,06/2024,Spanish,Spanish,8,Pablo Trujillo,4.8,22,92,1,Software Development Tools

### __10/ Check range of data__

In [56]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Duration,24501.0,9.745614,12.916868,0.5,3.0,5.5,11.5,439.5
Total Lectures,24501.0,73.255867,84.038107,3.0,26.0,46.0,86.0,800.0
Price,24501.0,547150.687727,334323.569753,299000.0,399000.0,399000.0,399000.0,2499000.0
Total Enrollments,24501.0,6903.546712,35468.189982,0.0,150.0,797.0,3655.0,2026921.0
Avg Rating Score,24501.0,4.273683,1.908527,0.0,4.1,4.4,4.6,31.1
Total Ratings,24501.0,662.907351,6739.433869,0.0,15.0,62.0,229.0,531611.0
Total Sections,24501.0,10.334762,9.980066,1.0,5.0,8.0,13.0,287.0
Avg Ins Rating,24331.0,4.351305,0.360191,0.0,4.2,4.4,4.5,5.0
Total Ins Reviews,24501.0,23334.116322,94585.682335,0.0,204.0,1637.0,10550.0,1252252.0
Total Ins's Students,24501.0,160017.421983,404596.002137,0.0,2648.0,19750.0,103054.0,4193832.0
Total Ins's Courses,24501.0,61.319130,165.495854,1.0,3.0,10.0,33.0,1541.0

In [98]:
# Max Avg Rating Score is 31.1 => Wrong => Update 
df = df[df['Avg Rating Score'] <= 5.0]

# __III/ Data Modeling__

### __1/ Create LANGUAGE table__

In [99]:
# Create new DISTINCT VALUE DATAFRAME for SUBTITLES and LANGUAGE  
sub_list = (
        df['Subtitles']
        .str.split(',')
        .explode()
        .str.strip()
        .drop_duplicates()
        .replace('', pd.NA)
        .dropna()
        .reset_index(drop=True)
)
lang_list = df['Language'].drop_duplicates().reset_index(drop=True)

# Merge 2 DF and drop DUPLICATE 
full_lang = pd.concat([sub_list, lang_list]).drop_duplicates().sort_values().reset_index(drop=True)
Language = pd.DataFrame(full_lang, columns = ['Language'])
Language['Language_ID'] = Language.index + 1

Language

               Language  Language_ID
0             Afrikaans            1
1              Albanian            2
2                Arabic            3
3                 Azeri            4
4               Bengali            5
5             Bulgarian            6
6               Burmese            7
7               Catalan            8
8              Croatian            9
9                 Czech           10
10               Danish           11
11                Dutch           12
12              English           13
13             Estonian           14
14             Filipino           15
15              Finnish           16
16               French           17
17             Georgian           18
18               German           19
19                Greek           20
20               Hebrew           21
21                Hindi           22
22            Hungarian           23
23           Indonesian           24
24              Italian           25
25             Japanese           26
26               Korean           27
27           Lithuanian           28
28                Malay           29
29            Malayalam           30
30              Marathi           31
31              Persian           32
32               Polish           33
33           Portuguese           34
34             Romanian           35
35              Russian           36
36   Simplified Chinese           37
37               Slovak           38
38               Somali           39
39              Spanish           40
40              Swedish           41
41                Tamil           42
42               Telugu           43
43                 Thai           44
44  Traditional Chinese           45
45              Turkish           46
46            Ukrainian           47
47                 Urdu           48
48           Vietnamese           49

### __2/ Create Mini_Subject table__

In [100]:
cate_list = (df['Mini_Subject']
             .str.split(',')
             .explode()
             .str.strip()
             .drop_duplicates()
             .reset_index(drop=True)
             )

Mini_Subject = pd.DataFrame(cate_list) 
Mini_Subject['Mini_Subject_ID'] = Mini_Subject.index + 1  

Mini_Subject = Mini_Subject.rename(columns={'Mini_Subject' : 'Mini_Subject_Name'})
Mini_Subject

               Mini_Subject_Name  Mini_Subject_ID
0  Database Design & Development                1
1             Mobile Development                2
2          Programming Languages                3
3           Software Engineering                4
4                Web Development                5
5               Software Testing                6
6                   Data Science                7
7     Software Development Tools                8
8            No-Code Development                9
9               Game Development               10

### __3/ Create INSTRUCTOR table__

In [101]:
Ins = df[['Instructor Name', "Total Ins's Courses", "Total Ins's Students", 'Total Ins Reviews', "Avg Ins Rating"]].drop_duplicates().reset_index(drop=True)

# Lấy chỉ số của bản ghi có Total Ins's Students lớn nhất cho mỗi Instructor Name
max_students_idx = Ins.groupby("Instructor Name")["Total Ins's Students"].idxmax()

Instructor = Ins.loc[max_students_idx].reset_index(drop=True)

Instructor['Instructor_ID'] = Instructor.index + 1 

Instructor

,Instructor Name,Total Ins's Courses,Total Ins's Students,Total Ins Reviews,Avg Ins Rating,Instructor_ID
0,#NAME?,2,33062,642,4.3,1
1,(사) 한국디지털컨버전스협회,10,672,152,4.5,2
2,- Skillcoach -,7,10331,4657,4.5,3
3,.NET University,9,8106,858,4.6,4
4,0aaa Club,1,235,92,4.5,5
...,...,...,...,...,...,...
8922,형선 최,1,420,133,4.7,8923
8923,홍드로이드 이홍철,5,2579,374,4.5,8924
8924,황선수닷컴 hwangsunsoo,6,399,143,4.3,8925
8925,황영덕 (Sean) Youngdeok Hwang,1,1223,211,4.7,8926
8926,훈상 (Hoon-Sang) 윤 (Yun),11,858,195,4.2,8927

### __4/ Create COURSE table__

In [102]:
Course = (df[['Course Name', 'Language', 'Level', 'Duration',
             'Total Sections', 'Total Lectures', 'Total Enrollments',
             'Avg Rating Score', 'Total Ratings', 'Last Updated',
            'Price', 'URL', 'Instructor Name']]
            .drop_duplicates()
            .reset_index(drop = True))

Course['Course_ID'] = Course.index + 1

Course

,Course Name,Language,Level,Duration,Total Sections,Total Lectures,Total Enrollments,Avg Rating Score,Total Ratings,Last Updated,Price,URL,Instructor Name,Course_ID
0,如何从0-1搭建内容推荐系统,Simplified Chinese,Beginner,1.0,3,9,21,5.0,3,09/2021,399000,https://www.udemy.com/course/0-1-vvuy/,三节课 sanjieke,1
1,0 dan İleri Seviye Swift 5 ile İOS Mobil Uygul...,Turkish,All Levels,18.0,11,95,6331,3.1,61,04/2019,399000,https://www.udemy.com/course/0-dan-ileri-seviy...,Hüseyin Can KINCAL,2
2,0-dan Python proqramlaşdırma ümumi izahda,Azeri,Beginner,10.0,17,101,8,4.2,3,02/2022,399000,https://www.udemy.com/course/0-dan-python-proq...,Rəsul Eminli,3
3,非同步程式設計從0到1,Traditional Chinese,All Levels,5.0,4,35,56,4.7,13,11/2020,2499000,https://www.udemy.com/course/01-async/,Rico Chen,4
4,01 Day C Code | Learn C Programming with Examp...,English,All Levels,3.0,9,29,17956,4.0,167,01/2025,399000,https://www.udemy.com/course/01-day-c-code-lea...,Faisal Zamir,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24391,دورة تصميم برنامج المبيعات و المخازن بلغة السي...,Arabic,Beginner,44.0,1,55,19,5.0,1,09/2024,399000,https://www.udemy.com/course/zwjteeml/,Mohammed Nageh,24392
24392,金融业务增长秘籍之：核心指标体系的搭建与拆解,Simplified Chinese,Intermediate,0.5,3,7,30,4.9,3,09/2021,399000,https://www.udemy.com/course/zxaylrnf/,三节课 sanjieke,24393
24393,CNC Programming in Hindi (सीएनसी प्रोग्रामिंग ...,Hindi,All Levels,6.0,1,11,82,4.2,16,07/2022,399000,https://www.udemy.com/course/zxppxplw/,Mech Trainers,24394
24394,Zynq Training - Learn Zynq 7000 SOC device on ...,English,Beginner,2.5,9,21,4595,3.7,163,07/2020,399000,https://www.udemy.com/course/zynq-training-lea...,Augmented Startups,24395
24395,Zynq Esencial,Spanish,Intermediate,10.0,8,24,92,4.8,22,06/2024,649000,https://www.udemy.com/course/zynq7000-esencial/,Pablo Trujillo,24396

### __5/ Create COURSE-Mini_Subject table__

In [103]:
Course_Mini_Subject = (df[['Course Name', 'Mini_Subject']]
                   .drop_duplicates()
                   .reset_index(drop=True))

# Split Mini_Subject by delimeter AGAIN
Course_Mini_Subject['Mini_Subject'] = Course_Mini_Subject['Mini_Subject'].str.split(',')

Course_Mini_Subject = Course_Mini_Subject.explode('Mini_Subject').reset_index(drop = True)

Course_Mini_Subject['Mini_Subject'] = Course_Mini_Subject['Mini_Subject'].str.strip()

# Merge COURSE 
Course_Mini_Subject = Course_Mini_Subject.merge(Course[['Course Name', 'Course_ID']], on = 'Course Name', how = 'left')

# Merge Mini_Subject  
Course_Mini_Subject =  Course_Mini_Subject.merge(Mini_Subject[['Mini_Subject_Name','Mini_Subject_ID']],left_on = 'Mini_Subject', right_on = 'Mini_Subject_Name', how = 'left')

# Final table 
Course_Mini_Subject = Course_Mini_Subject[['Course_ID', 'Mini_Subject_ID']]

Course_Mini_Subject

       Course_ID  Mini_Subject_ID
0              1                1
1              2                2
2              3                3
3              4                3
4              5                3
...          ...              ...
24403      24392                3
24404      24393                7
24405      24394                3
24406      24395                4
24407      24396                8

[24408 rows x 2 columns]

### __6/ Create COURSE-SUBTITLES table__

In [104]:
Course_Subtitles = (df[['Course Name', 'Subtitles']]
                    .drop_duplicates()
                    .reset_index(drop = True)
                    )

# Split SUBTITLES by ,
Course_Subtitles['Subtitles'] = Course_Subtitles['Subtitles'].str.split(',')

Course_Subtitles = Course_Subtitles.explode('Subtitles').reset_index(drop=True)

Course_Subtitles['Subtitles'] = Course_Subtitles['Subtitles'].str.strip()

# Remove COURSE RECORD which has no subtitles 
Course_Subtitles = Course_Subtitles[Course_Subtitles['Subtitles'] != '']

# Get course_id from COURSE table 
Course_Subtitles = Course_Subtitles.merge(Course, on = 'Course Name', how = 'left')

# Get language_id (for subtitles) from LANGUAGE table 
Course_Subtitles = Course_Subtitles.merge(Language, left_on = 'Subtitles', right_on = 'Language', how = 'left')

Course_Subtitles = Course_Subtitles[['Course_ID', 'Language_ID']]

## __IV/ Export to CSV file__

In [105]:
Language.to_csv("Language.csv", index=False, encoding="utf-8-sig")
Mini_Subject.to_csv("Mini_Subject.csv", index=False, encoding="utf-8-sig")
Instructor.to_csv("Instructor.csv", index=False, encoding="utf-8-sig")
Course.to_csv("Course.csv", index=False, encoding="utf-8-sig")
Course_Mini_Subject.to_csv("Course_Mini_Subject.csv", index=False, encoding="utf-8-sig")
Course_Subtitles.to_csv("Course_Subtitles.csv", index=False, encoding="utf-8-sig")